final List<Map<String, String>> countryList = [
  {'flag': '🇦🇫', 'code': '93', 'name': 'Afghanistan', 'short': 'AF'},
  {'flag': '🇦🇱', 'code': '355', 'name': 'Albania', 'short': 'AL'},
  {'flag': '🇩🇿', 'code': '213', 'name': 'Algeria', 'short': 'DZ'},
  {'flag': '🇦🇩', 'code': '376', 'name': 'Andorra', 'short': 'AD'},
  {'flag': '🇦🇴', 'code': '244', 'name': 'Angola', 'short': 'AO'},
  {'flag': '🇦🇷', 'code': '54', 'name': 'Argentina', 'short': 'AR'},
  {'flag': '🇦🇲', 'code': '374', 'name': 'Armenia', 'short': 'AM'},
  {'flag': '🇦🇺', 'code': '61', 'name': 'Australia', 'short': 'AU'},
  {'flag': '🇦🇹', 'code': '43', 'name': 'Austria', 'short': 'AT'},
  {'flag': '🇦🇿', 'code': '994', 'name': 'Azerbaijan', 'short': 'AZ'},
  {'flag': '🇧🇭', 'code': '973', 'name': 'Bahrain', 'short': 'BH'},
  {'flag': '🇧🇩', 'code': '880', 'name': 'Bangladesh', 'short': 'BD'},
  {'flag': '🇧🇪', 'code': '32', 'name': 'Belgium', 'short': 'BE'},
  {'flag': '🇧🇷', 'code': '55', 'name': 'Brazil', 'short': 'BR'},
  {'flag': '🇨🇦', 'code': '1', 'name': 'Canada', 'short': 'CA'},
  {'flag': '🇨🇳', 'code': '86', 'name': 'China', 'short': 'CN'},
  {'flag': '🇪🇬', 'code': '20', 'name': 'Egypt', 'short': 'EG'},
  {'flag': '🇫🇷', 'code': '33', 'name': 'France', 'short': 'FR'},
  {'flag': '🇩🇪', 'code': '49', 'name': 'Germany', 'short': 'DE'},
  {'flag': '🇮🇳', 'code': '91', 'name': 'India', 'short': 'IN'},
  {'flag': '🇮🇶', 'code': '964', 'name': 'Iraq', 'short': 'IQ'},
  {'flag': '🇮🇹', 'code': '39', 'name': 'Italy', 'short': 'IT'},
  {'flag': '🇯🇵', 'code': '81', 'name': 'Japan', 'short': 'JP'},
  {'flag': '🇰🇼', 'code': '965', 'name': 'Kuwait', 'short': 'KW'},
  {'flag': '🇲🇾', 'code': '60', 'name': 'Malaysia', 'short': 'MY'},
  {'flag': '🇲🇽', 'code': '52', 'name': 'Mexico', 'short': 'MX'},
  {'flag': '🇲🇦', 'code': '212', 'name': 'Morocco', 'short': 'MA'},
  {'flag': '🇳🇱', 'code': '31', 'name': 'Netherlands', 'short': 'NL'},
  {'flag': '🇳🇿', 'code': '64', 'name': 'New Zealand', 'short': 'NZ'},
  {'flag': '🇳🇬', 'code': '234', 'name': 'Nigeria', 'short': 'NG'},
  {'flag': '🇳🇴', 'code': '47', 'name': 'Norway', 'short': 'NO'},
  {'flag': '🇴🇲', 'code': '968', 'name': 'Oman', 'short': 'OM'},
  {'flag': '🇵🇰', 'code': '92', 'name': 'Pakistan', 'short': 'PK'},
  {'flag': '🇵🇭', 'code': '63', 'name': 'Philippines', 'short': 'PH'},
  {'flag': '🇶🇦', 'code': '974', 'name': 'Qatar', 'short': 'QA'},
  {'flag': '🇷🇺', 'code': '7', 'name': 'Russia', 'short': 'RU'},
  {'flag': '🇸🇦', 'code': '966', 'name': 'Saudi Arabia', 'short': 'SA'},
  {'flag': '🇿🇦', 'code': '27', 'name': 'South Africa', 'short': 'ZA'},
  {'flag': '🇰🇷', 'code': '82', 'name': 'South Korea', 'short': 'KR'},
  {'flag': '🇪🇸', 'code': '34', 'name': 'Spain', 'short': 'ES'},
  {'flag': '🇸🇪', 'code': '46', 'name': 'Sweden', 'short': 'SE'},
  {'flag': '🇨🇭', 'code': '41', 'name': 'Switzerland', 'short': 'CH'},
  {'flag': '🇹🇷', 'code': '90', 'name': 'Turkey', 'short': 'TR'},
  {'flag': '🇦🇪', 'code': '971', 'name': 'United Arab Emirates', 'short': 'AE'},
  {'flag': '🇬🇧', 'code': '44', 'name': 'United Kingdom', 'short': 'GB'},
  {'flag': '🇺🇸', 'code': '1', 'name': 'United States', 'short': 'US'},
  {'flag': '🇻🇳', 'code': '84', 'name': 'Vietnam', 'short': 'VN'},
];
